# Generated by Django 4.2.2 on 2023-06-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('year', models.DateField(default=0, null=True)),
                ('description', models.TextField(default='Video Game', null=True)),
            ],
        ),
    ]
